"""
Django settings for leisuretimezapi project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import environ
import os
from pathlib import Path
from .wrapper import SSHDBWrapper

# Make sure to close the SSH tunnel when Django shuts down
import atexit
# Initialize environ
env = environ.Env()

# Read .env file
environ.Env.read_env()

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = os.environ.get('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = []
# ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS').split(',')

STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET ='whsec_2d3d993432cae72eccbc51daa01c1d5fb89e5b2290ddbd514c0d016ca1b34537'
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9_%bo458navh+f7pzr#awrq*y3!yy0q&-77p9dgy+pr-0%#!es'	

# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django.contrib.humanize',
    'index',
    'myadmin',
    'django.contrib.sitemaps',
    'django.contrib.sites',
    'rest_framework.authtoken',
    # 'dj_rest_auth',
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'dj_rest_auth.registration',

]
# ACCOUNT_USER_MODEL_USERNAME_FIELD=None
# ACCOUNT_USERNAME_REQUIRED = False
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
]
REST_FRAMEWORK = {
   'DEFAULT_AUTHENTICATION_CLASSES': (
       'rest_framework.authentication.TokenAuthentication',
   )
}




ROOT_URLCONF = 'leisuretimezapi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'leisuretimezapi.wsgi.application'
AUTH_USER_MODEL = 'index.CustomUser'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Initialize SSH tunnel
db_wrapper = SSHDBWrapper()
db_wrapper.connect()

# Database configuration
DATABASES = {
    'default': db_wrapper.get_database_config()
}


atexit.register(db_wrapper.close)
# DATABASES = {
#     'default': {
#         'ENGINE': 'mysql.connector.django',
#         'NAME': 'findepbl_leisuretimez_data',
#         'USER': 'findepbl_leisuretimez',
#         'PASSWORD': 'K1Z#vApAn7KA',
#         'HOST': 'www.leisuretimez.com',
#         'PORT': '3306',
#         'OPTIONS': {'init_command': "SET sql_mode='STRICT_TRANS_TABLES'" ,"use_pure": True},

#     }
# }

# localhost
# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
MEDIA_URL = 'https://media.leisuretimez.com/'
STATIC_URL = 'static/'
STATIC_ROOT='/home/findepbl/leisuretimez/static'
# MEDIA_ROOT='/home/findepbl/leisuretimez/media'
MEDIA_ROOT='/home/findepbl/leisuretimezmedia'
STATICFILES_DIRS = [
    '/home/findepbl/leisuretimez/public/static'
]

# Email backend configuration (using Anymail with Mailgun as an example)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# Template configuration (for email templates)
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'support@leisuretimez.com'
EMAIL_HOST_PASSWORD = 'babadadacac'
DEFAULT_FROM_EMAIL = 'support@leisuretimez.com'
SITE_ID = 1
DOMAIN = 'leisuretimez.com'
SITE_NAME = 'leisuretimez'
ADMIN_EMAIL='contact@leisuretimez.com'
CONTACT_FROM_EMAIL = 'contact@leisuretimez.com'
