# Generated by Django 5.2.11 on 2026-02-28 23:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_seed_lookup_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_key",
                    models.CharField(
                        db_index=True,
                        help_text="The auth token key for this session",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_fingerprint",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "device_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Parsed device/browser name from user-agent",
                        max_length=255,
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="False when session has been revoked/expired",
                    ),
                ),
                ("last_activity", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="active_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        default="",
                        help_text="Captured at log time (survives account deletion)",
                        max_length=254,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login_success", "Login Success"),
                            ("login_failed", "Login Failed"),
                            ("logout", "Logout"),
                            ("password_changed", "Password Changed"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_confirmed", "Password Reset Confirmed"),
                            ("account_activated", "Account Activated"),
                            ("account_deactivated", "Account Deactivated"),
                            ("account_deleted", "Account Deleted"),
                            ("token_expired", "Token Expired"),
                            ("throttle_triggered", "Throttle Triggered"),
                            ("lockout_triggered", "Lockout Triggered"),
                            ("concurrent_session", "Concurrent Session Detected"),
                            ("new_device", "New Device Detected"),
                            ("suspicious_activity", "Suspicious Activity"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                ("user_agent", models.TextField(blank=True, default="")),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 hash of user-agent + IP for device tracking",
                        max_length=64,
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="low",
                        max_length=10,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional context (old IP, geo info, error messages, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="index_usera_user_id_4c315e_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-created_at"],
                        name="index_usera_ip_addr_80b1e2_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="index_usera_action_02db08_idx",
                    ),
                ],
            },
        ),
    ]
