# Generated by Django 5.2.11 on 2026-02-25 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0002_seed_lookup_tables"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Booking Created"),
                            ("updated", "Booking Updated"),
                            ("status_changed", "Status Changed"),
                            ("quote_created", "Quotation Created"),
                            ("quote_revised", "Quotation Revised"),
                            ("quote_accepted", "Quotation Accepted"),
                            ("quote_rejected", "Quotation Rejected"),
                            ("invoice_created", "Invoice Created"),
                            ("invoice_adjusted", "Invoice Adjusted"),
                            ("invoice_cancelled", "Invoice Cancelled"),
                            ("payment_received", "Payment Received"),
                            ("payment_failed", "Payment Failed"),
                            ("refund_issued", "Refund Issued"),
                            ("message_sent", "Message Sent"),
                            ("attachment_uploaded", "Attachment Uploaded"),
                            ("assigned", "Staff Assigned"),
                            ("cancelled", "Booking Cancelled"),
                            ("note_added", "Admin Note Added"),
                        ],
                        db_index=True,
                        max_length=25,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Human-readable description of what happened"
                    ),
                ),
                (
                    "old_value",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Previous value (for status changes, quote amounts, etc.)",
                    ),
                ),
                (
                    "new_value",
                    models.TextField(
                        blank=True, default="", help_text="New value after the action"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional structured data (quotation_id, invoice_id, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="booking_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_log",
                        to="index.personalisedbooking",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalisedBookingInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. PBI-000001",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("partially_paid", "Partially Paid"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("adjusted", "Adjusted"),
                            ("cancelled", "Cancelled"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("due_date", models.DateField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("adjustment_reason", models.TextField(blank=True, default="")),
                (
                    "original_total",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total before adjustment; NULL = no adjustment made",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, default="")),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="index.personalisedbooking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pb_invoices_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PersonalisedBookingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. PBP-XXXXXX",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("installment", "Installment"),
                            ("final_balance", "Final Balance"),
                            ("full_payment", "Full Payment"),
                            ("refund", "Refund"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("wallet", "Wallet"),
                            ("bank_transfer", "Bank Transfer"),
                            ("split", "Split (Wallet + Stripe)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "stripe_session_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "stripe_payment_intent_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "wallet_transaction_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "transaction_reference",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="index.personalisedbookinginvoice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_name",
                    models.CharField(
                        help_text='e.g. "Deposit", "Second installment", "Final balance"',
                        max_length=100,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("due_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("upcoming", "Upcoming"),
                            ("due", "Due"),
                            ("paid", "Paid"),
                            ("overdue", "Overdue"),
                            ("waived", "Waived"),
                        ],
                        default="upcoming",
                        max_length=10,
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("position", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_schedule",
                        to="index.personalisedbooking",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_items",
                        to="index.personalisedbookinginvoice",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        help_text="The payment that fulfilled this milestone",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedule_items",
                        to="index.personalisedbookingpayment",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quotation_number",
                    models.CharField(
                        db_index=True,
                        help_text="Auto-generated, e.g. QTN-000001-v1",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("viewed", "Viewed"),
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="Tax percentage (e.g. 7.5)",
                        max_digits=5,
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "discount_reason",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Terms, conditions, inclusions/exclusions",
                    ),
                ),
                (
                    "payment_terms",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text='e.g. "50% deposit on acceptance, balance 14 days before event"',
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True,
                        help_text="Quote expiry date; NULL = no expiry",
                        null=True,
                    ),
                ),
                (
                    "revision_reason",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Why this revision was created",
                        max_length=255,
                    ),
                ),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                ("rejected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotations",
                        to="index.personalisedbooking",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="The quotation this version supersedes",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_version",
                        to="index.quotation",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "unique_together": {("booking", "version")},
            },
        ),
        migrations.AddField(
            model_name="personalisedbookinginvoice",
            name="quotation",
            field=models.ForeignKey(
                blank=True,
                help_text="The accepted quotation this invoice is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="invoices",
                to="index.quotation",
            ),
        ),
        migrations.CreateModel(
            name="QuotationLineItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=500)),
                ("quantity", models.PositiveIntegerField(default=1)),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="line_items",
                        to="index.quotation",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional link to service catalog; NULL for custom items",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.servicecatalog",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
            },
        ),
    ]
