# Generated by Django 5.2.11 on 2026-02-26 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0003_bookingactivitylog_personalisedbookinginvoice_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="auto_cancelled",
            field=models.BooleanField(
                default=False,
                help_text="True if this booking was cancelled by the system (not the user)",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("booking_confirmed", "Booking Confirmed"),
                    ("payment_received", "Payment Received"),
                    ("trip_reminder", "Trip Reminder"),
                    ("booking_cancelled", "Booking Cancelled"),
                    ("booking_auto_cancelled", "Booking Auto-Cancelled"),
                    ("duplicate_booking_warning", "Duplicate Booking Warning"),
                    ("refund_processed", "Refund Processed"),
                    ("promo", "Promotion"),
                    ("system", "System"),
                    ("new_blog_post", "New Blog Post"),
                    ("blog_comment", "Blog Comment"),
                    ("blog_reaction", "Blog Reaction"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
