# Generated by Django 5.2.11 on 2026-03-04 13:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0004_biometricdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PushDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fcm_token",
                    models.TextField(
                        help_text="FCM registration token from the mobile SDK",
                        unique=True,
                    ),
                ),
                (
                    "device_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Device identifier for dedup across token refreshes",
                        max_length=255,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "device_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="push_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
