# Generated by Django 5.2.11 on 2026-03-12 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("index", "0005_pushdevice"),
    ]

    operations = [
        migrations.CreateModel(
            name="PricingTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_adult_count", models.PositiveIntegerField()),
                ("min_children_count", models.PositiveIntegerField(default=0)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pricing_tiers",
                        to="index.package",
                    ),
                ),
            ],
            options={
                "ordering": ["min_adult_count", "min_children_count"],
            },
        ),
    ]
